apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment-service
  template:
    metadata:
      labels:
        app: enrollment-service
    spec:
      containers:
        - name: enrollment-service
          image: localhost:5000/enrollment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082


---
apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
spec:
  type: NodePort
  selector:
    app: enrollment-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30085